import { Schema, model } from 'mongoose';
import { applyToJSON } from '../utils/toJSON';
const owner = { type: Schema.Types.ObjectId, required: true, index: true };
const settings = new Schema({ userId: { ...owner, unique: true }, enabled: { type: Boolean, default: false }, maxPerDay: { type: Number, default: 3 }, quietStart: { type: String, default: '22:00' }, quietEnd: { type: String, default: '07:00' }, tone: { type: String, default: 'FIRM' }, language: { type: String, default: 'vi' }, snoozedUntil: { type: String, default: null } }, { timestamps: true });
applyToJSON(settings);
export const CoachSettingsModel = model('CoachSettings', settings);
const message = new Schema({ userId: owner, requestId: String, role: { type: String, enum: ['user', 'assistant'], required: true }, content: { type: String, required: true } }, { timestamps: true });
message.index({ userId: 1, requestId: 1, role: 1 }, { unique: true });
applyToJSON(message);
export const CoachMessageModel = model('CoachMessage', message);
const checkin = new Schema({ userId: owner, date: { type: String, required: true }, energy: Number, difficulty: Number, note: String }, { timestamps: true });
checkin.index({ userId: 1, date: 1 }, { unique: true });
applyToJSON(checkin);
export const CoachCheckInModel = model('CoachCheckIn', checkin);
const request = new Schema({ userId: owner, requestId: { type: String, required: true }, kind: String, input: String, state: { type: String, enum: ['PENDING', 'DONE', 'FAILED'], default: 'PENDING' }, result: Schema.Types.Mixed, error: String }, { timestamps: true });
request.index({ userId: 1, requestId: 1 }, { unique: true });
export const CoachRequestModel = model('CoachRequest', request);
const review = new Schema({ userId: owner, date: String, kind: String, content: String }, { timestamps: true });
review.index({ userId: 1, date: 1, kind: 1 }, { unique: true });
export const CoachReviewModel = model('CoachReview', review);
const budget = new Schema({ userId: owner, date: String, channel: String, used: { type: Number, default: 0 }, claims: { type: [String], default: [] } });
budget.index({ userId: 1, date: 1, channel: 1 }, { unique: true });
export const CoachBudgetModel = model('CoachBudget', budget);
const job = new Schema({ userId: owner, key: { type: String, required: true }, kind: String, date: String, planId: String, activityId: String, state: { type: String, default: 'PENDING' }, dueAt: Date, expiresAt: Date, leaseUntil: Date, attempt: { type: Number, default: 0 }, tickets: { type: [Schema.Types.Mixed], default: [] }, ticketHistory: { type: [Schema.Types.Mixed], default: [] }, acceptedAt: Date, receiptCheckedAt: Date, openedAt: Date, error: String }, { timestamps: true });
job.index({ userId: 1, key: 1 }, { unique: true });
job.index({ state: 1, dueAt: 1 });
applyToJSON(job);
export const CoachPushJobModel = model('CoachPushJob', job);
