import type { Locale } from "@/stores/languageStore";

export type Movement = "bench" | "incline" | "fly" | "pushup" | "deadlift" | "row" | "pullup" | "pulldown" | "press" | "raise" | "curl" | "hammer" | "pushdown" | "squat" | "rdl" | "legpress" | "hipthrust" | "legraise";
export interface ExerciseGuide {
  movement: Movement;
  steps: Record<Locale, string[]>;
  tip: Record<Locale, string>;
}
const guide = (movement: Movement, vi: string[], en: string[], tipVi: string, tipEn: string): ExerciseGuide => ({
  movement, steps: { vi, en }, tip: { vi: tipVi, en: tipEn },
});
// Original FitTrack instructions and schematic movement data, not third-party media.
export const exerciseGuides: Record<string, ExerciseGuide> = {
  "Bench Press": guide("bench",
    ["Nằm trên ghế ngang, đặt chân vững và giữ bả vai ổn định trên ghế.", "Hạ thanh tạ có kiểm soát về phía ngực, rồi đẩy lên; giữ cổ tay thẳng với cẳng tay."],
    ["Lie on a flat bench with feet planted and shoulder blades stable against the bench.", "Lower the bar under control toward your chest, then press up with wrists aligned over your forearms."],
    "Không nảy thanh tạ trên ngực; dùng chốt an toàn hoặc người hỗ trợ khi cần.", "Do not bounce the bar off your chest; use safety arms or a spotter when needed."),
  "Incline Dumbbell Press": guide("incline",
    ["Tựa lưng trên ghế dốc nhẹ, hai chân vững; giữ hai tạ ở hai bên ngực.", "Đẩy tạ lên trên ngực, rồi hạ chậm về vị trí đầu."],
    ["Sit against a slightly inclined bench with feet planted and dumbbells beside your chest.", "Press the weights above your chest, then lower slowly to the starting position."],
    "Giữ vai ổn định, tránh nhún vai hoặc đập hai tạ vào nhau.", "Keep your shoulders stable; avoid shrugging or knocking the weights together."),
  "Cable Fly": guide("fly",
    ["Đứng vững giữa hai dây cáp, khuỷu tay hơi gập và giữ thân ổn định.", "Khép hai tay theo vòng cung trước ngực, rồi mở tay chậm."],
    ["Stand steadily between two cables with slightly bent elbows and a stable torso.", "Bring your hands together in an arc in front of your chest, then open slowly."],
    "Giữ góc khuỷu tay gần như không đổi, tránh kéo vai quá sâu ra sau.", "Keep your elbow angle nearly constant and avoid pulling the shoulders too far back."),
  "Push-up": guide("pushup",
    ["Chống hai tay xuống sàn, giữ thân thành một đường thẳng từ đầu đến gót chân.", "Gập khuỷu hạ ngực gần sàn, rồi đẩy người lên."],
    ["Place your hands on the floor and keep a straight line from head to heels.", "Bend your elbows to lower your chest toward the floor, then press up."],
    "Tránh võng lưng hoặc nhô hông; có thể chống tay lên bề mặt cao để giảm độ khó.", "Avoid sagging your back or lifting your hips; elevate your hands to make the movement easier."),
  "Deadlift": guide("deadlift",
    ["Đặt thanh tạ gần giữa bàn chân, gập hông và gối để nắm thanh, siết thân người.", "Đạp chân xuống sàn và đứng lên, giữ thanh gần chân; hạ tạ bằng cách đưa hông ra sau."],
    ["Position the bar near midfoot, bend your hips and knees to grip it, and brace your trunk.", "Push through the floor to stand, keeping the bar close to your legs; hinge back to lower it."],
    "Tránh giật tạ hoặc ngửa lưng quá mức ở đỉnh động tác.", "Avoid jerking the bar or leaning backward at the top."),
  "Barbell Row": guide("row",
    ["Gập hông, hơi chùng gối và giữ lưng ổn định; thả thanh tạ dưới vai.", "Kéo thanh về phía bụng dưới rồi hạ chậm, giữ thân gần như cố định."],
    ["Hinge at your hips with soft knees and a stable back; let the bar hang below your shoulders.", "Pull the bar toward your lower abdomen, then lower slowly while keeping your torso still."],
    "Tránh dùng hông hất tạ hoặc rướn cổ lên.", "Avoid swinging the weight with your hips or craning your neck."),
  "Pull-up": guide("pullup",
    ["Nắm xà, giữ thân ổn định và hai vai có kiểm soát.", "Kéo người lên bằng cách đưa khuỷu xuống, rồi hạ người chậm."],
    ["Grip the bar and stabilize your body with controlled shoulders.", "Pull yourself up by driving your elbows down, then lower slowly."],
    "Tránh đung đưa hoặc rướn cổ để vượt xà.", "Avoid swinging or reaching with your neck to clear the bar."),
  "Lat Pulldown": guide("pulldown",
    ["Ngồi vững, cố định đùi dưới đệm và nắm thanh kéo phía trên.", "Kéo thanh về phía ngực trên, rồi trả thanh lên có kiểm soát."],
    ["Sit firmly with your thighs under the pad and grip the overhead bar.", "Pull the bar toward your upper chest, then return it upward under control."],
    "Không kéo thanh ra sau gáy; tránh ngả người quá xa.", "Do not pull behind your neck; avoid leaning too far back."),
  "Overhead Press": guide("press",
    ["Đứng vững, siết bụng và giữ thanh tạ ở phía trước vai.", "Đẩy thanh qua đầu rồi hạ chậm về vai, giữ thân ổn định."],
    ["Stand firmly, brace your abdomen and hold the bar in front of your shoulders.", "Press the bar overhead, then lower slowly to your shoulders with a stable torso."],
    "Tránh ưỡn lưng để đưa tạ lên.", "Avoid arching your lower back to lift the weight."),
  "Lateral Raise": guide("raise",
    ["Đứng vững, hai tạ ở hai bên người và khuỷu hơi gập.", "Nâng tay sang hai bên đến khoảng ngang vai, rồi hạ chậm."],
    ["Stand steadily with dumbbells at your sides and elbows slightly bent.", "Raise your arms out to about shoulder height, then lower slowly."],
    "Tránh vung người và nhún vai để nâng tạ.", "Avoid swinging your body or shrugging to lift the weights."),
  "Barbell Curl": guide("curl",
    ["Giữ thanh tạ trước đùi, lòng bàn tay hướng lên và khuỷu gần thân.", "Gập khuỷu đưa tạ lên, rồi duỗi tay có kiểm soát."],
    ["Hold the bar in front of your thighs with palms facing up and elbows close to your sides.", "Bend your elbows to curl the bar up, then extend your arms under control."],
    "Giữ thân yên và cổ tay ổn định, tránh đẩy hông lấy đà.", "Keep your torso and wrists stable; avoid using your hips for momentum."),
  "Hammer Curl": guide("hammer",
    ["Cầm hai tạ với lòng bàn tay hướng vào nhau, khuỷu gần thân.", "Gập khuỷu nâng tạ, giữ cách cầm trung tính rồi hạ chậm."],
    ["Hold dumbbells with palms facing each other and elbows close to your sides.", "Curl the weights with the same neutral grip, then lower slowly."],
    "Tránh đưa khuỷu ra trước quá nhiều hoặc đung đưa người.", "Avoid moving your elbows too far forward or swinging your body."),
  "Triceps Pushdown": guide("pushdown",
    ["Đứng trước cáp cao, giữ khuỷu sát hai bên thân và nắm tay cầm.", "Duỗi khuỷu để đẩy tay cầm xuống, rồi gập khuỷu trở lại chậm."],
    ["Stand at a high cable with your elbows close to your sides and hold the handle.", "Extend your elbows to press the handle down, then bend them back slowly."],
    "Giữ cánh tay trên ổn định, tránh dùng cả thân người đè xuống.", "Keep your upper arms still; avoid pressing down with your entire torso."),
  "Squat": guide("squat",
    ["Đứng với khoảng chân phù hợp, giữ tạ chắc trên lưng trên và siết thân người.", "Gập hông và gối để hạ người trong tầm kiểm soát, rồi đạp chân đứng lên."],
    ["Stand with a comfortable stance, secure the bar across your upper back and brace your trunk.", "Bend your hips and knees to lower under control, then push through your feet to stand."],
    "Giữ bàn chân tiếp xúc sàn và đầu gối đi cùng hướng với ngón chân.", "Keep your feet planted and let your knees track in the direction of your toes."),
  "Romanian Deadlift": guide("rdl",
    ["Đứng cầm thanh tạ trước đùi, gối hơi chùng và lưng ổn định.", "Đưa hông ra sau để hạ tạ gần chân, rồi đưa hông về trước để đứng thẳng."],
    ["Stand holding the bar in front of your thighs with soft knees and a stable back.", "Push your hips back to lower the bar close to your legs, then bring your hips forward to stand."],
    "Dừng độ sâu khi không còn giữ được lưng ổn định; không cần chạm tạ xuống sàn.", "Stop lowering before losing your back position; the bar does not need to touch the floor."),
  "Leg Press": guide("legpress",
    ["Tựa lưng và hông vào ghế, đặt hai chân chắc trên bàn đạp.", "Hạ bàn đạp bằng cách gập gối trong tầm kiểm soát, rồi đẩy ra."],
    ["Keep your back and hips against the seat and plant your feet on the platform.", "Lower the platform by bending your knees under control, then press it away."],
    "Không để hông cuộn khỏi ghế hoặc khóa gối mạnh ở cuối lần đẩy.", "Avoid rolling your hips off the seat or forcefully locking your knees."),
  "Hip Thrust": guide("hipthrust",
    ["Tựa lưng trên vào ghế chắc, đặt chân trên sàn và đệm thanh tạ trên hông.", "Đẩy hông lên bằng cơ mông, rồi hạ xuống có kiểm soát."],
    ["Rest your upper back on a stable bench, plant your feet and pad the bar over your hips.", "Drive your hips upward using your glutes, then lower under control."],
    "Giữ cằm hơi thu và tránh ưỡn lưng quá mức ở đỉnh.", "Keep your chin slightly tucked and avoid overextending your lower back at the top."),
  "Hanging Leg Raise": guide("legraise",
    ["Treo người chắc trên xà, giữ vai và thân ổn định.", "Nâng chân về phía trước bằng bụng và hông, rồi hạ chậm; có thể gập gối để dễ hơn."],
    ["Hang securely from a bar with stable shoulders and torso.", "Lift your legs forward using your abdomen and hips, then lower slowly; bend your knees for an easier version."],
    "Tránh lấy đà hoặc đung đưa người giữa các lần nâng.", "Avoid using momentum or swinging between repetitions."),
};
export function getExerciseGuide(name: string, isCustom = false): ExerciseGuide | null {
  return !isCustom && Object.hasOwn(exerciseGuides, name) ? exerciseGuides[name] : null;
}
